### PR TITLE
Tag colors

### PR DESCRIPTION
**Pull request by conema**
This PR re-enable background color and text color for tagged email.

### CODE REVIEW

**Comment by FerSabGar** [comment]
It works nice.
Thanks a lot!

**Comment by FerSabGar** [comment]
@conema, you are using a color gradient for those lines tagged according to the tag color.

The result is nice.

After I was thinking that coherency could be enhanced if a gradient was also used in normal lines (for messages without any tag). So I tested a solution for monterail theme which consists in making some changes in "_based.ccs" to draw a gradient based on --message-list-background-color and --message-list-highlight-background-color variables.

The result is this one:
image

I know that making a gradient from the highlight background color (blue in monterail theme) to message list background color (white in monterail theme) is maybe excessive but in this way I've been able to use defined variables which is better in terms of personalization. I have not enough knowledge to play with a different opacity of the highlight background color. In addition, using variables could be useful to enhance this change to others styles.

Anyway, just take it as an idea to gain coherency.

The resulting code in _base.cc is:

```
#threadTree > treechildren::-moz-tree-row(selected) {
	border: none !important;
/*	background: var(--message-list-highlight-background-color) !important; */
/*	Background is printed as gradient for coherency with tag lines styles */
 	background: linear-gradient(var(--message-list-background-color),
                                    var(--message-list-highlight-background-color)) !important;
}

```
Thanks for your work.

**Comment by conema** [comment]
@spymastermatt If you want, may you set me contributor of this repository? 
It would be easier for me handle issues.

**Comment by conema** [comment]
I will open a new PR, this is messed up.

**Pull request closed without merging**
